FROM debian

ENV HOME /home/steam
ENV STEAMCMDDIR	$HOME/steamcmd
ENV GAMESRVDIR	$HOME/gamesrv
ENV SRVPORT	27015

RUN set -x \
	&& apt-get update \
	&& apt-get install -y --no-install-recommends --no-install-suggests \
		lib32stdc++6 \
		lib32gcc1 \
		wget \
		ca-certificates \
	&& apt-get clean autoclean \
	&& apt-get autoremove -y \
	&& rm -rf /var/lib/apt/lists/*
	
RUN useradd -m steam \
	&& su steam -c \
		"mkdir -p $STEAMCMDDIR \
		&& cd $STEAMCMDDIR \
		&& wget -qO- 'https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz' | tar zxf -"

EXPORT $SRVPORT
USER steam

ADD /scripts $DOCKERGO
RUN chmod -R 755 $DOCKERGO
ENTRYPOINT $DOCKERGO/server_init.sh
